spring:
  application:
    name: SOAP-Pedido
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/distribuidora_salvador_soap
      username: root
      password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true